### ISSUE TITLE
Modify Particle Spawner Count Over Time

### ISSUE THREAD

**Issue by morgenthum** [djeedai/bevy_hanabi#373] opened 2024-08-26 16:49 UTC
Hi there!

I created a rain particle effect, but I want to dynamically adjust the spawner count over time so that the rain gradually starts and stops. I attempted to implement this with the following code, but it doesn’t seem to have any effect:

```
fn update_effect_count(
    mut effects: ResMut<Assets<EffectAsset>>,
    effect_query: Query<&ParticleEffect>,
) {
    for effect in effect_query.iter() {
        let effect_asset = effects.get_mut(&effect.handle).unwrap();
        effect_asset.spawner.set_count(1.0.into());
    }
}
```

Could someone point out what I might be doing wrong or suggest an alternative approach?

**Comment by djeedai** [comment] 2024-08-26 18:20
Isn't this the same as #371 ?

**Comment by morgenthum** [comment] 2024-08-26 20:00
Oh yes, exactly!

**Comment by djeedai** [comment] 2024-08-27 06:39
Closing as duplicate of #371

**Closed by djeedai** 2024-08-27 06:39 UTC
