### ISSUE TITLE
Bevy 0.14.1 projects do not build due to compile error in Bevy_Hanabi 0.12.1

### ISSUE THREAD

**Issue by ShreyK** [djeedai/bevy_hanabi#360] opened 2024-08-04 13:46 UTC
**Crate versions**
`bevy` version: 0.14.1
`bevy_hanabi` version: 0.12.1
**Describe the bug**

**Expected behavior**
Cannot build a bevy 0.14.1 project with bevy_hanabi version (0.12.1) 
I think a namespace collision for `size_of`

**To Reproduce**
Building a Bevy 0.14.1 project with latest bevy_hanabi version (0.12.1)

**Screenshots**
![image](https://github.com/user-attachments/assets/e7d22769-b282-4edb-9e85-6830ecb9a833)

**Comment by martinmolin** [comment] 2024-08-04 14:54
I had the same issue, however updating Rust through `rustup update` worked for me. Not sure if was something cache issue or not.

**Comment by jf908** [comment] 2024-08-04 15:17
It seems https://github.com/djeedai/bevy_hanabi/commit/0663370ccc37d831faeba1d3a049f9522df6957d fixed a lint error but also made it incompatible with Rust 1.79.0

**Comment by djeedai** [comment] 2024-08-04 15:31
Bevy itself has been locked on 1.79 MSRV, and therefore you shouldn't build with anything older.

https://github.com/bevyengine/bevy/commit/9055fc1d68bc3ee0f965ad0d101b7e777a184e17

Closing as by design. Building Bevy with rust < 1.79 is not supported.

**Comment by jf908** [comment] 2024-08-04 22:42
> Closing as by design. Building Bevy with rust < 1.79 is not supported.

I think you misread, bevy_hanabi is now only compatible with Rust 1.80 which is 1 version later than bevy's locked version.

**Comment by djeedai** [comment] 2024-08-05 07:53
Need to remove linter `unused_qualifications`, the adding of `size_of` to the prelude in rustc 1.80 is a breaking change we can't otherwise support with MSRV 1.79 (Bevy). 😡

**Comment by djeedai** [comment] 2024-08-05 16:34
Published v0.12.2 without the linter option, and reverted the removal of `std::mem::`; this should make it work on both 1.79 and 1.80 hopefully (CI now builds with MSRV check in addition of stable).

**Closed by djeedai** 2024-08-05 16:34 UTC
Labels: C - bug
