### ISSUE TITLE
OSX bug – only the particles from the first spawned ParticleEffectBundle are getting updates

### ISSUE THREAD

**Issue by zaycev** [djeedai/bevy_hanabi#171] opened 2023-03-28 05:35 UTC
**Version**
_This is critical, please fill. The code is evolving fast, and many bugs get fixed. If you're not on latest please try first on latest release if you can, chances are the bug is fixed there._
`bevy` version: 0.10
`bevy_hanabi` version: 0.6.1

**Describe the bug**
See attached YT video. Only the particles from the first spawned ParticleEffectBundle are getting updates. Other particles are spawned with their initial parameters and never updated. This is only happening on OSX (I've tested on both – Intel and Apple Silicon machines), on Windows everything works as expected. 

**To Reproduce**
On OSX:
```
cargo run --features="bevy/bevy_winit bevy/bevy_pbr 3d" --example multicam
```

**Screenshots**
https://youtu.be/zx0Ky8DzGb0?t=15

**Comment by djeedai** [comment] 2023-03-28 06:29
Duplicate of #165

**Closed by djeedai** 2023-03-28 06:29 UTC
Labels: bug
