### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by jaynnn** [djeedai/bevy_hanabi#268] opened 2024-01-16 10:38 UTC
`bevy` version:0.12
`bevy_hanabi` version: 0.10.0-dev
sub dependencies:
> naga="0.14.2"
> naga_oil="0.11.0"
> wgpu="0.18.0"
> bevy-inspector-egui="0.22.1"

error[E0277]: the trait bound `ComposableModuleDescriptor<'_>: From<&bevy::prelude::Shader>` is not satisfied
   --> src\render\mod.rs:446:38
    |
446 |                     (&common_shader).into();
    |                                      ^^^^ the trait `From<&bevy::prelude::Shader>` is not implemented for `ComposableModuleDescriptor<'_>`
    |
    = note: required for `&bevy::prelude::Shader` to implement `Into<ComposableModuleDescriptor<'_>>`

error[E0271]: type mismatch resolving `<Module as ToOwned>::Owned == Module`
    --> src\render\mod.rs:463:55
     |
463  | ...Source::Naga(Cow::Owned(naga_module)),
     |                 ^^^^^^^^^^^^^^^^^^^^^^^ expected `naga::Module`, found a different `naga::Module`
     |
     = note: `naga::Module` and `naga::Module` have similar names, but are actually distinct types

**Comment by jaynnn** [comment] 2024-01-16 10:51
Seems like all dependencies up to date could make this compile error.

**Comment by jaynnn** [comment] 2024-01-16 14:31
Yes, it is. sorry for bothering.

**Comment by djeedai** [comment] 2024-01-17 07:37
No bother. But I don't have the time to support Bevy's `main` branch and all its breaking changes, so I only update on new releases. In-between you have to wait or fix it yourself.

**Comment by jpedrick** [comment] 2024-02-13 20:57
> No bother. But I don't have the time to support Bevy's `main` branch and all its breaking changes, so I only update on new releases. In-between you have to wait or fix it yourself with a local fork.

I have this compiling against bevy `main`. The fixes were trivial but many. Would you consider a `bevy_0_13` branch?

**Comment by djeedai** [comment] 2024-02-14 10:54
I have to check with the maintainers when is the next Bevy 0.13 coming up. Generally I don't look at branches against `main` unless the next Bevy release is imminent, in which case I do welcome a pre-upgraded branch (that saves me some time and makes the crate release more likely to happen earlier).

**Comment by jpedrick** [comment] 2024-02-14 16:38
@djeedai I saw in the #general channel on Discord that the 0.13 release is imminent. 

While patching up the examples I ran into this error:
```
thread 'main' panicked at .../naga-0.19.0/src/back/glsl/mod.rs:1193:44:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
```

The specific line in Naga is a match case:

```
            // Textures and samplers are handled directly in `Writer::write`.
            crate::AddressSpace::Handle => unreachable!(),
```

And the stack trace is many layers deep in naga-oil/naga. So, it may be a bug in one of those libraries that is calling `write_global` instead of `Writer::write`

Running with `--release` seems to bypass the problem.

**Comment by djeedai** [comment] 2024-02-14 18:13
@robtfm for visibility on possible `naga_oil` bug while upgrading to `main` ahead of Bevy 0.13. I haven't checked myself, but there's some details above. Thanks

**Comment by robtfm** [comment] 2024-02-14 19:26
Sounds like a naga issue - naga_oil is just requesting glsl output for the wgsl input. 

You could try using the naga oil cli (link from one of naga_oil’s open issues) to output the complete shader in wgsl and then run it through naga’s own cli. That should produce the same error, then the naga team can look into it. 

if you don’t manage/don’t have time pls link the example that’s failing and I’ll try and do it in a few days

**Comment by jpedrick** [comment] 2024-02-14 21:01
Hi @robtfm , I've updated my branch to use bevy from git(previously I was using a pull from around one month ago). There are two examples(circle and init) that are failing in debug mode still, but is slightly different.

```rust
thread 'main' panicked at /Users/jpedrick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/naga-0.19.0/src/back/glsl/mod.rs:1193:44:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_core_pipeline::upscaling::prepare_view_upscaling_pipelines`!
2024-02-14T20:59:53.625495Z  WARN bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
2024-02-14T20:59:53.625513Z  WARN bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
2024-02-14T20:59:53.625520Z  WARN bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
2024-02-14T20:59:53.625528Z  WARN bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
2024-02-14T20:59:53.625543Z  WARN bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
2024-02-14T20:59:53.625548Z  WARN bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
thread 'main' panicked at /Users/jpedrick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by jpedrick** [comment] 2024-02-18 03:00
Hi @robtfm and @djeedai, Bevy 0.13 is released as of today! I've updated my fork and it should be good to go.

**Comment by djeedai** [comment] 2024-02-18 20:56
This is failing on this binding from `mesh_view_bindings.wgsl` (full name: `diffuse_environment_mapsX_naga_oil_mod_XMJSXM6K7OBRHEOR2NVSXG2C7OZUWK527MJUW4ZDJNZTXGX`):

```wgsl
@group(0) @binding(13) var diffuse_environment_maps: binding_array<texture_cube<f32>, 8u>;
```

The global variable has an address space of `naga::AddressSpace::Handle`, and the actual type is `naga::TypeInner::BindingArray`. Binding arrays are not supported in GLSL by naga yet; see https://github.com/gfx-rs/wgpu/issues/4537 and related issues (mentioned in comments).

This GLSL comes from the validation that `naga_oil` performs, when its `glsl` feature is active:

https://github.com/bevyengine/naga_oil/blob/33e57e488660aaeee81fa928454e51c215f9d0be/src/compose/mod.rs#L1151-L1155

The source of the issue is that Bevy itself disables that feature, but Hanabi had it enabled via default features. Disabling it fixes the issue.

I'm closing this issue, there's nothing more to see here :)

**Closed** 2024-02-18 21:00 UTC
Labels: invalid
